call mvn clean install
start java -jar target/hazelcast-0.0.1.jar
start java -jar target/hazelcast-0.0.1.jar
start java -jar target/hazelcast-0.0.1.jar
start java -jar target/hazelcast-0.0.1.jar
start java -jar target/hazelcast-0.0.1.jar
start java -jar target/hazelcast-0.0.1.jar
start java -jar target/hazelcast-0.0.1.jar
start java -jar target/hazelcast-0.0.1.jar
start java -jar target/hazelcast-0.0.1.jar
start java -jar target/hazelcast-0.0.1.jar